"""Subclass of Ppal, which is generated by wxFormBuilder."""

import wx
import abm
import wx.lib.masked.ctrl as masked

from gui.controls import *
import gettext
_ = gettext.gettext


# Implementing Ppal
class ABMPpal( abm.Ppal ):
	
	def __init__( self, parent ):
		abm.Ppal.__init__( self, parent )
		SizerControles = wx.BoxSizer( wx.VERTICAL )

		fgSizer = wx.GridSizer( rows=3, cols=2, hgap=0, vgap=0 )
		
		self.m_staticText2 = wx.StaticText( self.pagEdicion, wx.ID_ANY, _(u"CUIT"), wx.DefaultPosition, wx.DefaultSize, 0 )
		self.m_staticText2.Wrap( -1 )
		fgSizer.Add( self.m_staticText2, 0, wx.ALL|wx.ALIGN_RIGHT, 5 )
		
		self.cuit = textbox.wx_masked_TextCtrl( self.pagEdicion, -1, '', mask = '##-########-#')
		fgSizer.Add(self.cuit, 0, wx.ALL|wx.ALL, 5)
		
		self.lblNombre = wx.StaticText( self.pagEdicion, wx.ID_ANY, _(u"Nombre"), wx.DefaultPosition, wx.DefaultSize, 0 )
		fgSizer.Add( self.lblNombre, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
		
		self.txtNombre = textbox.wx_masked_TextCtrl(self.pagEdicion, -1, '', mask = "XXXXXXXXXXXXXXXXXXXXX", formatcodes="S!")
		fgSizer.Add(self.txtNombre, 0, wx.ALL|wx.ALL, 5)
		
		SizerControles.Add( fgSizer, 1, wx.EXPAND, 5 )
		
		bSizer61 = wx.BoxSizer( wx.HORIZONTAL )
		
		self.btnGraba = button.wx_BitmapButton( self.pagEdicion, wx.ID_ANY, wx.Bitmap( u"imagenes/save-b.png", wx.BITMAP_TYPE_ANY ), wx.DefaultPosition, wx.DefaultSize, wx.BU_AUTODRAW )
		
		self.btnGraba.SetBitmapDisabled( wx.Bitmap( u"imagenes/save-b.png", wx.BITMAP_TYPE_ANY ) )
		self.btnGraba.SetBitmapSelected( wx.Bitmap( u"imagenes/save.png", wx.BITMAP_TYPE_ANY ) )
		self.btnGraba.SetBitmapFocus( wx.Bitmap( u"imagenes/save.png", wx.BITMAP_TYPE_ANY ) )
		self.btnGraba.SetBitmapHover( wx.Bitmap( u"imagenes/save.png", wx.BITMAP_TYPE_ANY ) )
		bSizer61.Add( self.btnGraba, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.EXPAND, 5 )
		
		self.btnCancela = button.wx_BitmapButton( self.pagEdicion, wx.ID_ANY, wx.Bitmap( u"imagenes/SALIR_D.bmp", wx.BITMAP_TYPE_ANY ), wx.DefaultPosition, wx.DefaultSize, wx.BU_AUTODRAW )
		
		self.btnCancela.SetBitmapDisabled( wx.Bitmap( u"imagenes/SALIR_D.bmp", wx.BITMAP_TYPE_ANY ) )
		self.btnCancela.SetBitmapSelected( wx.Bitmap( u"imagenes/SALIR.bmp", wx.BITMAP_TYPE_ANY ) )
		self.btnCancela.SetBitmapFocus( wx.Bitmap( u"imagenes/SALIR.bmp", wx.BITMAP_TYPE_ANY ) )
		self.btnCancela.SetBitmapHover( wx.Bitmap( u"imagenes/SALIR.bmp", wx.BITMAP_TYPE_ANY ) )
		bSizer61.Add( self.btnCancela, 1, wx.ALL|wx.EXPAND, 5 )
		
		SizerControles.Add( bSizer61, 0, wx.EXPAND, 5 )
				
		self.pagEdicion.SetSizer( SizerControles )
		self.pagEdicion.Layout()
		SizerControles.Fit( self.pagEdicion )
		self.Paginas.SetSelection(0)

		self.btnGraba.Bind( wx.EVT_BUTTON, self.btnGrabaOnButtonClick )
		self.btnCancela.Bind( wx.EVT_BUTTON, self.btnCancelaOnButtonClick )			
	
	# Handlers for Ppal events.
	def txtBusquedaOnChar( self, event ):
		# TODO: Implement txtBusquedaOnChar
		pass
	
	def btnAgregaOnButtonClick( self, event ):
		# TODO: Implement btnAgregaOnButtonClick
		self.Paginas.SetSelection(1)
	
	def btnEditarOnButtonClick( self, event ):
		# TODO: Implement btnEditarOnButtonClick
		self.Paginas.SetSelection(1)
	
	def btnBorrarOnButtonClick( self, event ):
		# TODO: Implement btnBorrarOnButtonClick
		pass
	
	def btnSalirOnButtonClick( self, event ):
		# TODO: Implement btnSalirOnButtonClick
		self.Close()
	
	def btnCancelaOnButtonClick( self, event ):
		self.Paginas.SetSelection(0)
		event.Skip()
	
	def btnGrabaOnButtonClick( self, event ):
		event.Skip()
	
	
class App(wx.App):
	
	def OnInit(self):
		try:
			frame = ABMPpal(None)
			frame.Show(True)
			return True
		except RuntimeError as err:
			print "Ha ocurrido un error y no podemos iniciar el sistema"
			print err
			return False


if __name__ == '__main__':
	app = App()
	app.MainLoop()
